version: 2
jobs:
  build:
    working_directory: ~/java-tron
   # - run: curl http://60.205.215.34/stest_20190117162111_dir/dailyBuild/index.html
    - run: open http://60.205.215.34/stest_20190117162111_dir/dailyBuild/index.html






